language: python

sudo: false

python: 3.5

addons:
  apt:
    packages:
    - nodejs
    - npm

install:
  - pip install tox coveralls

branches:
  only:
    - master
    - develop

# Explicit environments list here is a complete list of environments from tox.
# It is intentionally shortened.
env:
  - TOX_ENV=flake8

# python 2.7
  - TOX_ENV=py27-dj16-thumbs1x
  - TOX_ENV=py27-dj16-thumbs2x
  - TOX_ENV=py27-dj17-thumbs2x
  - TOX_ENV=py27-dj18-thumbs2x
  - TOX_ENV=py27-dj19-thumbs2x

# python 3.4
  - TOX_ENV=py34-dj16-thumbs2x
  - TOX_ENV=py34-dj17-thumbs2x
  - TOX_ENV=py34-dj18-thumbs2x
  - TOX_ENV=py34-dj19-thumbs2x

# python 3.5
  - TOX_ENV=py35-dj18-thumbs2x
  - TOX_ENV=py35-dj19-thumbs2x

# next Django release
  - TOX_ENV=py27-djmaster-thumbs2x
  - TOX_ENV=py34-djmaster-thumbs2x
  - TOX_ENV=py35-djmaster-thumbs2x

  - TOX_ENV=frontend

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls --config_file=.coveragerc
  - mkdir -p shippable/codecoverage && cp coverage.xml shippable/codecoverage/coverage.xml

matrix:
  allow_failures:
    - env: TOX_ENV=py27-djmaster-thumbs2x
    - env: TOX_ENV=py34-djmaster-thumbs2x
    - env: TOX_ENV=py35-djmaster-thumbs2x
